spring:
    profiles: 
        active: local 
    h2:
      console:
        enabled: true
    datasource:
      url: jdbc:h2:mem:mydb
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
    resources:
      static-locations: 
      - classpath:/static/
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: 821564819362-nag0ge4u3skdp8v3ffb4752vul5oof7o.apps.googleusercontent.com
              client-secret: NzIQxH-VGVxWqZz9flDEMROg
                
          


server:
  servlet:
    context-path: /api
  port: 8080