spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
  resources:
    static-locations: 
    - classpath:/static/
    - classpath:/samples/  
server:
     port: 8080          
   
---
 
spring:
  profiles: local      
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/invoice_manager
    username: invoice-manager
    password: hola123
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view:  true
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 821564819362-nag0ge4u3skdp8v3ffb4752vul5oof7o.apps.googleusercontent.com
            client-secret: NzIQxH-VGVxWqZz9flDEMROg         

---

spring:
  profiles: dev         
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-52-52-101-173.us-west-1.compute.amazonaws.com:3306/invoice_manager
    username: invoice-manager
    password: hola123
  jpa:
    hibernate:
      ddlAuto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
    hibernate.ddl-auto: none
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 821564819362-nag0ge4u3skdp8v3ffb4752vul5oof7o.apps.googleusercontent.com
            client-secret: NzIQxH-VGVxWqZz9flDEMROg

---

spring:
  profiles: stg         
  
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-13-52-209-95.us-west-1.compute.amazonaws.com:3306/invoice_manager
    username: invoice-manager
    password: hola123
  jpa:
    hibernate:
      ddlAuto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
    hibernate.ddl-auto: none
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 821564819362-nag0ge4u3skdp8v3ffb4752vul5oof7o.apps.googleusercontent.com
            client-secret: NzIQxH-VGVxWqZz9flDEMROg
            