spring:
    profiles: 
        active: local 
    datasource:
      url: jdbc:h2:mem:mydb
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
    resources:
      static-locations: 
      - classpath:/static/
  


server:
  servlet:
    context-path: /api
  port: 8080